modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (28 is current forge version)
[[mods]] #mandatory
modId="ncwdsteelmod" #mandatory
version="0.1" #mandatory
displayName="ncwd's Steel Mod" #mandatory
authors="ncwd"
description='''
Turn iron into steel
'''

[[dependencies.ncwdsteelmod]] #optional    
    modId="forge" #mandatory    
    mandatory=true #mandatory    
    versionRange="[28,)" #mandatory   
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
